//
//  CountryCodeModel.swift
//  LifeCykul
//
//  Created by Rishop Babu on 25/03/25.
//

import Foundation

struct CountryCodeModel: Identifiable, Codable {
    var id: UUID = UUID()
    let code: String
    let name: String
    
    static let allCountries: [CountryCodeModel] = [
        .init(code: "+91", name: "India"),
        .init(code: "+93", name: "Afghanistan"),
        .init(code: "+355", name: "Albania"),
        .init(code: "+213", name: "Algeria"),
        .init(code: "+376", name: "Andorra"),
        .init(code: "+244", name: "Angola"),
        .init(code: "+54", name: "Argentina"),
        .init(code: "+374", name: "Armenia"),
        .init(code: "+61", name: "Australia"),
        .init(code: "+43", name: "Austria"),
        .init(code: "+994", name: "Azerbaijan"),
        .init(code: "+973", name: "Bahrain"),
        .init(code: "+880", name: "Bangladesh"),
        .init(code: "+375", name: "Belarus"),
        .init(code: "+32", name: "Belgium"),
        .init(code: "+501", name: "Belize"),
        .init(code: "+229", name: "Benin"),
        .init(code: "+975", name: "Bhutan"),
        .init(code: "+591", name: "Bolivia"),
        .init(code: "+387", name: "Bosnia and Herzegovina"),
        .init(code: "+267", name: "Botswana"),
        .init(code: "+55", name: "Brazil"),
        .init(code: "+673", name: "Brunei"),
        .init(code: "+359", name: "Bulgaria"),
        .init(code: "+226", name: "Burkina Faso"),
        .init(code: "+257", name: "Burundi"),
        .init(code: "+855", name: "Cambodia"),
        .init(code: "+237", name: "Cameroon"),
        .init(code: "+1", name: "Canada"),
        .init(code: "+238", name: "Cape Verde"),
        .init(code: "+86", name: "China"),
        .init(code: "+57", name: "Colombia"),
        .init(code: "+506", name: "Costa Rica"),
        .init(code: "+385", name: "Croatia"),
        .init(code: "+53", name: "Cuba"),
        .init(code: "+357", name: "Cyprus"),
        .init(code: "+420", name: "Czech Republic"),
        .init(code: "+45", name: "Denmark"),
        .init(code: "+253", name: "Djibouti"),
        .init(code: "+593", name: "Ecuador"),
        .init(code: "+20", name: "Egypt"),
        .init(code: "+503", name: "El Salvador"),
        .init(code: "+372", name: "Estonia"),
        .init(code: "+251", name: "Ethiopia"),
        .init(code: "+679", name: "Fiji"),
        .init(code: "+358", name: "Finland"),
        .init(code: "+33", name: "France"),
        .init(code: "+241", name: "Gabon"),
        .init(code: "+995", name: "Georgia"),
        .init(code: "+49", name: "Germany"),
        .init(code: "+233", name: "Ghana"),
        .init(code: "+30", name: "Greece"),
        .init(code: "+502", name: "Guatemala"),
        .init(code: "+224", name: "Guinea"),
        .init(code: "+592", name: "Guyana"),
        .init(code: "+509", name: "Haiti"),
        .init(code: "+504", name: "Honduras"),
        .init(code: "+36", name: "Hungary"),
        .init(code: "+354", name: "Iceland"),
        .init(code: "+62", name: "Indonesia"),
        .init(code: "+98", name: "Iran"),
        .init(code: "+964", name: "Iraq"),
        .init(code: "+353", name: "Ireland"),
        .init(code: "+972", name: "Israel"),
        .init(code: "+39", name: "Italy"),
        .init(code: "+81", name: "Japan"),
        .init(code: "+962", name: "Jordan"),
        .init(code: "+7", name: "Kazakhstan"),
        .init(code: "+254", name: "Kenya"),
        .init(code: "+965", name: "Kuwait"),
        .init(code: "+996", name: "Kyrgyzstan"),
        .init(code: "+856", name: "Laos"),
        .init(code: "+371", name: "Latvia"),
        .init(code: "+961", name: "Lebanon"),
        .init(code: "+218", name: "Libya"),
        .init(code: "+423", name: "Liechtenstein"),
        .init(code: "+370", name: "Lithuania"),
        .init(code: "+352", name: "Luxembourg"),
        .init(code: "+261", name: "Madagascar"),
        .init(code: "+60", name: "Malaysia"),
        .init(code: "+960", name: "Maldives"),
        .init(code: "+223", name: "Mali"),
        .init(code: "+356", name: "Malta"),
        .init(code: "+230", name: "Mauritius"),
        .init(code: "+52", name: "Mexico"),
        .init(code: "+373", name: "Moldova"),
        .init(code: "+377", name: "Monaco"),
        .init(code: "+976", name: "Mongolia"),
        .init(code: "+212", name: "Morocco"),
        .init(code: "+258", name: "Mozambique"),
        .init(code: "+264", name: "Namibia"),
        .init(code: "+977", name: "Nepal"),
        .init(code: "+31", name: "Netherlands"),
        .init(code: "+64", name: "New Zealand"),
        .init(code: "+234", name: "Nigeria"),
        .init(code: "+47", name: "Norway"),
        .init(code: "+968", name: "Oman"),
        .init(code: "+92", name: "Pakistan"),
        .init(code: "+507", name: "Panama"),
        .init(code: "+595", name: "Paraguay"),
        .init(code: "+51", name: "Peru"),
        .init(code: "+63", name: "Philippines"),
        .init(code: "+48", name: "Poland"),
        .init(code: "+351", name: "Portugal"),
        .init(code: "+974", name: "Qatar"),
        .init(code: "+40", name: "Romania"),
        .init(code: "+7", name: "Russia"),
        .init(code: "+250", name: "Rwanda"),
        .init(code: "+966", name: "Saudi Arabia"),
        .init(code: "+221", name: "Senegal"),
        .init(code: "+65", name: "Singapore"),
        .init(code: "+27", name: "South Africa"),
        .init(code: "+82", name: "South Korea"),
        .init(code: "+34", name: "Spain"),
        .init(code: "+94", name: "Sri Lanka"),
        .init(code: "+46", name: "Sweden"),
        .init(code: "+41", name: "Switzerland"),
        .init(code: "+963", name: "Syria"),
        .init(code: "+886", name: "Taiwan"),
        .init(code: "+255", name: "Tanzania"),
        .init(code: "+66", name: "Thailand"),
        .init(code: "+216", name: "Tunisia"),
        .init(code: "+90", name: "Turkey"),
        .init(code: "+256", name: "Uganda"),
        .init(code: "+971", name: "United Arab Emirates"),
        .init(code: "+44", name: "United Kingdom"),
        .init(code: "+1", name: "United States"),
        .init(code: "+998", name: "Uzbekistan"),
        .init(code: "+58", name: "Venezuela"),
        .init(code: "+84", name: "Vietnam"),
        .init(code: "+260", name: "Zambia"),
        .init(code: "+263", name: "Zimbabwe")
    ]
}

